### ISSUE TITLE
Cannot use extension by using "Load packed extension..." in Developer Mode of Chrome

### ISSUE THREAD

**Issue by ghost** [risq/discogs-sort-plus#1]
Failed to load extension from: ~\Desktop\discogs-sort-plus-master
Could not load extension icon 'assets/icon_16x16.png'.
----------
If I manually copy the "assets" folder from src to the extension's root folder:

Failed to load extension from: ~\Desktop\discogs-sort-plus-master
Could not load javascript 'common.js' for content script.
----------
I do not see any "common.js" in the extension package. I do not know what to do with "gulpfile.js" as there are no instructions and this is getting into programmer territory, which I am not.

Please make the extension easier to install for people who are not adept with Chrome extension source code, it would be very appreciated. We want these features added to Discogs search, but with the convenience of ease of installation for the rest of us who are not programmers. Thanks! :)

**Comment by risq** [comment]
I've planned to make a clean release of the extension to the chrome store for a long time, but I've never took the time to do it (mainly because I didn't thought someone else would be interested in the extension).

I'll try to make a release soon. There are a few things needed before it's fully usable.

I'll keep you in touch !

**Comment by risq** [comment]
Here it is : https://chrome.google.com/webstore/detail/discogs-sort-plus/ckhcnelkpddhclnfodmmhfimeecbggna?hl=fr
